
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: rate_photos_development


test:
  <<: *default
  database: rate_photos_test

production:
  <<: *default
  database: rate_photos_production
  username: postgress
  password: <%= ENV['RATE_MY_PHOTOS_DATABASE_PASSWORD'] %>
